schedule

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -104,25 +104,40 @@
 
 # ---------------------------------------------------------------------
 
-name: if 조건 연습
+# name: if 조건 연습
+# on:
+#   push:
+#     branches:
+#       - develop
+#       - main
+
+# jobs:
+#   if-test:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: 테스트 실행
+#         id: run-tests
+#         # exit 1으로 실패시키기
+#         run: |
+#           echo "실패한 경우"
+#           exit 1
+
+#       - name: 테스트 실패 알림 (예시. 슬랙 혹은 디스코드)
+#         if: failure() # 이전 스텝이 실패했을 때만 실행
+#         run: |
+#           echo "테스트 실패 알림을 보내는 로직을 구현"
+
+# ---------------------------------------------------------------------
+
+name: 스케줄 작업
 on:
-  push:
-    branches:
-      - develop
-      - main
+  schedule:
+    # 매일 자정(UTC)에 실행
+    - cron: "0 0 * * *"
 
 jobs:
-  if-test:
+  scheduled-job:
     runs-on: ubuntu-latest
     steps:
-      - name: 테스트 실행
-        id: run-tests
-        # exit 1으로 실패시키기
-        run: |
-          echo "실패한 경우"
-          exit 1
-
-      - name: 테스트 실패 알림 (예시. 슬랙 혹은 디스코드)
-        if: failure() # 이전 스텝이 실패했을 때만 실행
-        run: |
-          echo "테스트 실패 알림을 보내는 로직을 구현"
+      - name: 정기 작업 실행
+        run: echo "스케줄에 따라 실행되는 작업입니다."
